title: "Luyifan's Blog"
tagline: "looks like a shell/terminal"
description: "This is a preview of jekyll-shell-theme."
github_username: obsidian0215
email: obsidian0215@gmail.com
baseurl: ""
url: "https://luyifan.top"

remote_theme: "tareqdandachi/jekyll-shell-theme"

plugins:
  - jemoji
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-seo-tag

sass:
  style: compressed

highlighter: rouge

header_pages:
  - index.md
  - read-me.md
  - preview.md

# set the size of the text to 'large' or 'small', default is small
font-size: small
